# Generated by Django 4.2.6 on 2023-10-26 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=127)),
                ('model', models.CharField(max_length=127)),
                ('manufacture_date', models.DateField()),
                ('description', models.TextField(max_length=255)),
                ('seats', models.IntegerField()),
                ('doors', models.IntegerField()),
                ('suitcases', models.IntegerField()),
                ('transmission', models.CharField(choices=[('AT', 'Automatic'), ('MN', 'Manual')], max_length=3)),
                ('air_conditioner', models.BooleanField(default=True)),
                ('min_driver_age', models.IntegerField(default=18)),
                ('car_exterior_photo', models.ImageField(upload_to='images/car_photos')),
                ('car_interior_photo', models.ImageField(upload_to='images/car_photos')),
                ('availability', models.BooleanField(default=True)),
                ('guarantee', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('deposit', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(max_length=127)),
                ('car_booked_from', models.DateTimeField(auto_now_add=True)),
                ('car_booked_to', models.DateTimeField(auto_now_add=True)),
                ('car_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.category')),
                ('car_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.class')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
