# Generated by Django 4.2.6 on 2023-10-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_booked_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_booked_to',
            field=models.DateTimeField(),
        ),
    ]
