# Generated by Django 4.2.6 on 2023-10-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_car_booked_from_alter_car_car_booked_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_booked_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_booked_to',
            field=models.DateField(),
        ),
    ]
