# Generated by Django 4.2.6 on 2023-10-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_car_booked_from_alter_car_car_booked_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='long_distance_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='per_km_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car_exterior_photo',
            field=models.ImageField(upload_to='static/images/car_photos'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_interior_photo',
            field=models.ImageField(upload_to='static/images/car_photos'),
        ),
    ]
