# Generated by Django 4.2.6 on 2023-11-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_long_distance_price_car_per_km_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/website_photos'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/website_photos'),
        ),
    ]
